Add conference class
francorojo/comfy-chair pull request #18
Opened 2024-08-05 03:41 UTC by francorojo

2024-08-05 20:57 UTC, NicoMadd commented on src/tests/dummies.ts
> +export const session2 = new Session(
Es la misma session que el de arriba. Por que el mismo dummy?

2024-08-05 20:57 UTC, NicoMadd commented on src/tests/dummies.ts
> +export const article2 = new RegularArticle(
Mismo article que el de arriba.

2024-08-08 22:23 UTC, NicoMadd commented on src/tests/dummies.ts
> +	'Pedro',
Por que cambiarlo a Pedro?

2024-08-08 22:27 UTC, NicoMadd commented on src/tests/conference.test.ts
> +		session.addArticle(article)
aca esta mal porque estas usando el objeto importado. Esto hace que en el test siguiente venga sucio con el article que agregues antes.

Tenes que instanciar una session con los dummies correspondientes. En todo caso, hace una dummy session con un article ya de por si.

2024-08-08 22:28 UTC, NicoMadd commented on src/tests/dummies.ts
> +export const session = new Session(
acordate de ponerle dummy adelante asi no hay dudas al hacer el import de que es efectivamente un dummy

2024-08-08 22:32 UTC, NicoMadd commented on src/tests/conference.test.ts
> +	test('Create a new conference and add Chair and Session correctly', () => {
Cuidado con los nombres de los tests. Es dificil de interpretar el correctamente. La descripcion del test debería ser intuitivo al testear sin caer a ver el codigo porque si el codigo esta mal entonces no sabemos si el test esta bien.

Fijate de con el mismo nombre expresar lo que queres probar. Si te sale mejor con codigo primero, fijate los expect que dejaste. Ej. _Conference sessions should match those added at first._ o _ Get authors should match those added._

2024-08-08 22:33 UTC, NicoMadd commented on src/tests/conference.test.ts
> +	test('Create a new conference with a user not organizer', () => {
Por ejemplo aca, deberias decir que al crear una organizacion con usuarios sin rol _ORGANIZER_ deberia arrojar una excepcion

2024-08-08 22:34 UTC, NicoMadd commented on src/tests/dummies.ts
> +	'Pedro',
En todo caso dejalo bien preparado con el mail y demas pero tene en cuenta que podrian romperse otros tests

2024-08-08 22:35 UTC, NicoMadd requested changes
Requiere cambios

2024-08-08 23:46 UTC, francorojo commented on src/tests/conference.test.ts
> +		session.addArticle(article)
Ciertoo!

2024-08-09 23:13 UTC, NicoMadd approved these changes

2024-08-09 23:17 UTC, merged